### ISSUE TITLE
bitbar gits nüm

### ISSUE THREAD

**Issue by oshovah** [Aareguru/aare.guru.bitbar#1]
Tschou, 

Sorry für d stööre, aber leider gits bitbar nüm. Es git aber e neustart wo xbar heisst. Leider bringi dert z aareguru.5m.php nid zum loufe. Är motzt wägere PATH variablä. Weni das gfixed ha, motzter wäge fork/exec zuegriff verwäärt... Has leider nid säuber härebracht :/

Aber ha dänkt ig mäude das mau :) Merci ömu für das geile plugin. Hani iz jahrelang brucht!! 

Auso, schööne, häbs guet

**Comment by cstuder** [comment]
Hallo, ja, gibt schon eine `xbar`-Version, nur noch nicht veröffentlicht. Dachte ausser mir brauche das niemand. ;-)

[aareguru.5m.php.zip](https://github.com/Aareguru/aare.guru.bitbar/files/8072260/aareguru.5m.php.zip)

Ich mach dann mal ein sauberes Repo und einen Verweis drauf.
